'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const noop=()=>{};
const nodes={},events={};
const node=id=>nodes[id]??={innerHTML:'',value:'',hidden:true,dataset:{},attributes:{},setAttribute(key,value){this.attributes[key]=value;},getAttribute(key){return this.attributes[key];},addEventListener:noop,querySelector:()=>node('heading'),querySelectorAll:()=>[],focus(){this.focused=true;},scrollIntoView(){this.scrolled=true;}};
const ids=['0','1','2','4','6','7','8'];
const buttons=ids.map(id=>({...node('milestone-'+id),dataset:{milestone:id},attributes:{}}));
const document={getElementById:node,querySelector:node,querySelectorAll:selector=>selector==='[data-milestone]'?buttons:[],addEventListener:(name,fn)=>events[name]=fn,documentElement:{dataset:{siteRoot:'../'},style:{setProperty:noop},classList:{add:noop,remove:noop,toggle:noop}}};
const context={document,location:new URL('https://coloradostreetbridgeproject.com/timeline/'),URL,URLSearchParams,addEventListener:noop,history:{pushState(_,__,href){context.location=new URL(href,context.location);}}};
vm.createContext(context);
for(const file of process.argv.includes('--bundle')?['assets/guide.js']:['search.js','speakers.js','other-speakers.js','resources.js','app.js'])vm.runInContext(read(file),context,{filename:file});
const run=code=>vm.runInContext(code,context);
const entries=JSON.parse(run('JSON.stringify(timeline)'));
assert.deepEqual(entries.filter(e=>e.milestone).map(e=>e.id),ids);
assert.equal(entries.length,11,'Keep all original chronology entries');
assert.equal(nodes['milestone-controls'].hidden,false,'Controls become available after enhancement');
for(const button of buttons){
  const entry=entries.find(e=>e.id===button.dataset.milestone);
  const beforeUrl=context.location.href;
  events.click({target:{closest:selector=>selector==='[data-milestone]'?button:null}});
  const html=nodes['milestone-detail'].innerHTML;
  assert.equal(context.location.href,beforeUrl,'Selecting a preview must not navigate or add history');
  assert(html.includes(run('esc('+JSON.stringify(entry.text)+')')),'Reuse the full-record text');
  assert(html.includes(run('esc('+JSON.stringify(entry.milestone.bridge)+')')));
  assert(html.includes('data-route="timeline/'+entry.id+'"'),'Each preview links to its original record');
  assert(html.includes('<h3 class="milestone-title">'),'Stable heading level after interaction');
  assert.equal(button.attributes['aria-pressed'],'true');
  assert.equal(buttons.filter(b=>b.attributes['aria-pressed']==='true').length,1);
  assert(!buttons.some(b=>b.focused),'Selection leaves keyboard focus on the activated button');
  assert.equal(html.includes('See the City’s design illustrations'),entry.id==='7');
}
const beforeInvalid=nodes['milestone-detail'].innerHTML;
run('selectMilestone("missing")');
assert.equal(nodes['milestone-detail'].innerHTML,beforeInvalid);
run('navigate("timeline/7",false)');
assert(nodes['milestone-detail'].innerHTML.includes('Jan–Jul 2024'),'Deep links select the matching preview');
assert.equal(buttons.find(b=>b.dataset.milestone==='7').attributes['aria-pressed'],'true');
const html=read('timeline/index.html');
assert(html.includes('aria-label="Choose a project milestone" hidden'),'No dead controls before JavaScript runs');
assert.equal((html.match(/data-milestone="/g)||[]).length,7);
assert.equal((html.match(/class="timeline-item"/g)||[]).length,11,'Static chronology remains complete');
assert(html.includes('aria-live="polite" aria-atomic="true"'));
assert(html.includes('<h3 class="milestone-title">'),'Static and dynamic heading levels match');
assert(html.includes('href="../timeline/#chronology"'));
assert(html.includes('href="../timeline/#forecast-heading"'));
assert(html.indexOf('id="milestone-heading"')<html.indexOf('id="chronology"'));
assert(html.indexOf('id="chronology"')<html.indexOf('id="forecast-heading"'));
for(const entry of entries){
  assert(html.includes('data-timeline-id="'+entry.id+'"'));
  assert(html.includes(run('esc('+JSON.stringify(entry.text)+')')),'Original chronology text retained');
}
assert(html.includes('https://www.nps.gov/places/colorado-street-bridge.htm'));
assert(html.includes('Selected milestones, not a time-scaled chart.'));
assert(html.includes('not a new live-status check'));
assert(!html.includes('assets/illustrations/'),'Do not misdate existing images as historical snapshots');
const css=read('styles.css');
assert(/\.milestone-controls\s*\{[^}]*flex-wrap:\s*wrap/.test(css));
assert(/\.milestone-button\s*\{[^}]*min-height:\s*48px/.test(css));
assert(/@media \(max-width: 600px\)\s*\{[^]*?\.milestone-tracks\s*\{\s*grid-template-columns:\s*minmax\(0,1fr\)/.test(css));
assert(/@media print\s*\{\s*\.milestone-explorer\s*\{\s*display:\s*none/.test(css));
console.log(JSON.stringify({mode:process.argv.includes('--bundle')?'bundle':'source',milestones:7,chronologyEntries:11,checks:'selection, no navigation, source linkage, stable headings, deep links, invalid IDs, full static chronology, responsive CSS guards, and print fallback passed'}));
